---
- name: Lamp stack installation
  hosts: servers

  tasks:
    - name: Apache installation on debian
      block: 
        - name: Install apache2
          apt: name=apache2 state=present

        - name: Enable and start apache2
          service: name=apache2 state=started enabled=yes
  
        - name: Add PHP repo 
          apt_repository: repo=ppa:ondrej/php state=present update_cache=yes

        - name: Install PHP7.xx
          apt: name=php7.3 state=present

      when: ansible_os_family == 'Debian'
      become: yes 
