---
- name: Lamp stack installation
  hosts: servers

  tasks:
    - name: Apache installation on debian
      block: 
        - name: Install apache2
          apt: name=apache2 state=present

        - name: Enable and start apache2
          service: name=apache2 state=started enabled=yes
    
        - name: Install apache modules
          apt: name=libapache2-mod-php7.3  state=present update_cache=yes

        - name: Add PHP repo 
          apt_repository: repo=ppa:ondrej/php state=present update_cache=yes

        - name: Install PHP7.xx
          apt: name=php7.3 state=present

        - name: Install php modules
          apt: name={{ item }} state=present update_cache=yes
          loop: [ 'php7.3-cli', 'php7.3-zip', 'php7.3-mysql', 'php7.3-curl' ]

        - name: Install MySQl
          apt: name=mysql-server state=present

        - name: Start mysql service  
          service: name=mysql state=started enabled=yes

      when: ansible_os_family == 'Debian'
      become: yes

    - name: Apache installation on RPM
      block:
        - name: Install HTTPD
          yum: name=httpd state=present

        - name: Enable and start httpd 
          service: name=httpd state=started enabled=yes

        - name: Install PHP dependencies
          yum: name={{ item }} state=present 
          loop: [ 'epel-release', 'yum-utils', 'http://rpms.remirepo.net/enterprise/remi-release-8.rpm' ]

        - name: Enable PHP repo
          yum: enablerepo=remi-php73  
          
        - name: Install PHP and modules
          yum: name={{ item }} state=present
          loop: [ 'php', 'php-common', 'php-opcache', 'php-cli', 'php-gd', 'php-curl', 'php-mysqlnd' ]  

        - name: Install Mysql 
          yum: name={{ item }} state=present
          loop: [ 'mysql', 'mysql-server' ]

        - name: start mysql service
          service: name=mysqld state=started enabled=yes

      when: ansible_os_family == 'RedHat'
      become: yes      
